### ISSUE TITLE
create a CLI to manage greenpress

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/greenpress-pm2#1]
cli package with node.

one install should do:
1. fork this repository.
2. git clone all sub-modules.
3. initiate data with the existing scripts.
4. ask the email and password, blog name and description, to initiate data with valid populated data.
5. explain scripts to run local environment and production.

**Comment by krishnanunnir** [comment]
Hey, can I work on this?

**Comment by davidmeirlevy** [comment]
> Hey, can I work on this?

Yes of course!

**Comment by krishnanunnir** [comment]
I am very inexperienced in working with Node and its frameworks, can you please tell me what all I should master in order to contribute to this project?

**Comment by davidmeirlevy** [comment]
There are several repositories connected to this repository, each has its own mechanism.
Most of them are node.ja projects.
The admin-panel is a frontend interface using vue, and the blog-front is using nuxt (a solution for vue with server-side rendering).
This repository was created in order to run all of those services together, in dev environment and on basic cloud solutions or node hosting solutions.
There will be another repositories that will make the same thing, but for docker solutions, such a docker-compose, swarm and k8s with helm charts.

About the CLI issue, it better be written using node.
I recommend using commander.js library.

**Comment by krishnanunnir** [comment]
Thanks a lot. That was really helpful.

**Comment by davidmeirlevy** [comment]
i'll close this issue here and move it to the new repository i made specifically for the cli:
https://github.com/greenpress/greenpress-cli

your'e welcome to continue working on the cli repo, i made the bootstrap work for it.

**Comment by krishnanunnir** [comment]
Ok, I will switch over to there

**Comment by davidmeirlevy** [comment]
Closed:
Z

Continue at the CLI dedicated repository:
https://github.com/greenpress/greenpress-cli/issues/1#issue-542007615

**Comment by davidmeirlevy** [comment]
@krishnanunnir 
His issue is waiting for you, if you like:
https://github.com/greenpress/greenpress-cli/issues/1#issue-542007615

Thanks.

**Comment by krishnanunnir** [comment]
Sorry for taking such a long time to respond, I will get working it.

**Comment by krishnanunnir** [comment]
Also is there any way to communicate with you? So that we can be sure on the implementation?
