### ISSUE TITLE
configuration api

### ISSUE THREAD

**Issue by sliron1989** [greenpress/greenpress-pm2#7]
1. to admin users - can get list of all configurations objects 
2. all the rest users - show all configuraion that
3. put request - admin can change metadata object and description
4. add description to collection in mongo
5. add description in project
type of configuration:
	1. version = system version and migration version.
	2. migration = managing migration status.
	3. app = admin users can change only this configuration.

**Comment by davidmeirlevy** [comment]
Duplicate
